version: '3.8'

services:
  mysql:
    image: mysql:8.0.39

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task_management_system
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    container_name: mysql
    healthcheck:
      test: ['CMD','mysqladmin','ping','-h','localhost']
      timeout: 20s
      retries: 10


  app:

    build: .
    ports:
      - "8080:8000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/task_management_system
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      mysql:
         condition: service_healthy

volumes:
  mysql-data:
